# Generated by Django 3.2.6 on 2022-05-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_rename_quontity_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.DateTimeField(blank=True, null=True, verbose_name='оплачен'),
        ),
    ]
